package net.dvdplay.promo;

public interface IPromoLookupTypes {
   int PROMO_VALIDATE_GOOD = 0;
   int PROMO_VALIDATE_NOSUCHCODE = 9000;
   int PROMO_VALIDATE_INVALID = 9001;
   int PROMO_VALIDATE_USED = 9002;
   int PROMO_VALIDATE_TOOEARLY = 9003;
   int PROMO_VALIDATE_EXPIRED = 9004;
   int PROMO_VALIDATE_WRONGTARGET = 9005;
   int PROMO_TARGET_TYPE_NONE = 0;
   int PROMO_TARGET_TYPE_PAYMENT_CARD = 1;
   int PROMO_TRACK_ENTITY_TYPE_NONE = 0;
   int PROMO_TRACK_ENTITY_TYPE_TRANSACTION = 1;
   int PROMO_TYPE_REUSABLE = 1;
   int PROMO_TYPE_USEONCE = 2;
   int PROMO_TYPE_USEONCEPERCARD = 3;
   int PROMO_TYPE_USEONCEPERUSER = 4;
   int PROMO_STATUS_VALID = 1;
   int PROMO_STATUS_INVALID = 2;
   int PROMO_STATUS_USED = 3;
   int PROMO_STATUS_EXPIRED = 4;
}
